# 服务端口
server:
  port: 9001

spring:
  application:
    name: cshop-user
  # redis配置
  data:
    redis:
      host: 116.198.217.158
      port: 6379
      password: MIIEowIBAAKCAQEAwG90ULRHmAXFXQzZSwleoYts2+bCzUvqhhqtGiv/F5kUsETY  # 如果有密码
      database: 0  # 默认数据库
      lettuce:
        pool:
          max-active: 100      # 最大连接数
          max-idle: 100        # 最大空闲连接数
          min-idle: 100        # 最小空闲连接数
          max-wait: 60000      # 最大等待时间，单位是毫秒

# 设置日志级别：ERROR/WARN/INFO/DEBUG,默认是 INFO 以上才显示
logging:
  level:
    root: INFO